[package]
name = "scratch_dl"
version = "0.1.0"
authors = ["suwa <unitedsuwa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.11.1"
numpy = "0.11.0"
ndarray = "*"
